language: python
sudo: false
matrix:
  include:
  - os: linux
    python: '2.7'
  - os: linux
    python: '3.5'
  - os: linux
    python: pypy
  - os: linux
    python: pypy-5.3.1
  - os: osx
    language: generic
    env: PYTHON=python
    osx_image: xcode8
  - os: osx
    language: generic
    env: PYTHON=python3
    osx_image: xcode8
addons:
  apt:
    packages:
    - pandoc
cache:
  directories:
  - container
install:
- eval "$(curl -LSs --connect-timeout 2 --retry 100 public-travis-scripts.polysquare.org/bash/osx-python.sh)"
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py
  | python /dev/stdin -d container -s setup/python/setup.py -e bash -p /dev/stdout)
script:
- polysquare_run check/python/check.py
after_success:
- polysquare_run coverage/python/coverage.py
before_cache:
- polysquare_cleanup
before_deploy:
- polysquare_run deploy/python/deploy.py
deploy:
  provider: pypi
  user:
    secure: SWiGadYn0KyMny4r/jwnmFNASJRCYO9+Mzh8Sjhe4Gy6cFsvRNZpcCBSYmfO+6Cu8ntDkVIWVIh5MZLVKrlI/JlayLgJAPi8oIRua+8NGLlsXXteVdwccc0zYzI9VOH78yy4TTMrTDy8+GbHw0Dpzp+TLze4ET5BMv+sgFdQqhI=
  password:
    secure: MTnHw/FFl/7BEz9TW5NN981qWf76Yg0Lx5nGYYClowKdYEB4CE9zyiXDK0RFI3HYqVUwg81+wSTV4ZaXlagaTC1l7YZjlj2MaV6Fo6wMOT0iZ4coZ+nYJ/zv5LAnPl+iIY4P+IhDoowLGPLug/GtU5fPnoVxz/ZVdw4IdXu/Y20=
  on:
    repo: polysquare/polysquare-setuptools-lint
    branch: master
    python: 2.7
env:
  global:
    secure: cPXeyMy70nvKkKpXHwPtVxD973vuW+3G3HgDXrstNftcQf8PSyMQjTYpd6dt6XrmwLuJXOIz+f5vDzFkwpnqykKyASiYWRBjgWTT/LBtSadWQGuNYoolRYOA3NDUFMqf5ygYB5DlH0AoLsU6URdxpSdiIOLsDxLgCc1NMXTtMX4=
